# Generated by Django 4.2.4 on 2023-10-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalmatrix',
            name='approval',
            field=models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual')], default='manual', max_length=6),
        ),
        migrations.AlterField(
            model_name='approvalmatrix',
            name='functionally',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='approvalmatrix',
            name='technically',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='', max_length=7),
        ),
    ]
