# Generated by Django 4.2.4 on 2023-10-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_approvalmatrix_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalmatrix',
            name='approval',
            field=models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual')], default='auto', max_length=6),
        ),
        migrations.AlterField(
            model_name='approvalmatrix',
            name='functionally',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=7),
        ),
        migrations.AlterField(
            model_name='approvalmatrix',
            name='technically',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=7),
        ),
    ]
