# Generated by Django 4.2.4 on 2023-10-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_alter_approvalmatrix_functionally_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalmatrix',
            name='approval',
            field=models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual')], max_length=6),
        ),
    ]
