# Generated by Django 4.2.4 on 2023-10-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_alter_approvalmatrix_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='functionality',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='technically',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='', max_length=7),
        ),
    ]
