# Generated by Django 4.2.4 on 2023-10-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_alter_subcategory_functionality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='functionality',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('other', 'Other')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='technically',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('other', 'Other')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='functionality',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('other', 'Other')], default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='technically',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('other', 'Other')], default='', max_length=7),
        ),
    ]
