# Generated by Django 4.2.4 on 2023-10-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_alter_approvalmatrix_functionally_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status_changed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
