# Generated by Django 4.2.4 on 2023-10-25 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_alter_item_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketFileTotalSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_file_size_kb', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.item')),
            ],
        ),
    ]
