# Generated by Django 4.2.4 on 2023-10-25 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_ticketfiletotalsize'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketfiletotalsize',
            options={'verbose_name_plural': 'Ticket File Total Sizes'},
        ),
    ]
