# Generated by Django 5.0.6 on 2024-07-29 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_alter_ticketfiletotalsize_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('inprogress', 'In Progress'), ('pending', 'Pending'), ('Resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='approvalmatrix',
            unique_together={('functionally', 'technically', 'approval')},
        ),
    ]
