# Generated by Django 5.0.6 on 2024-07-29 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_alter_item_status_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='approvalmatrix',
            unique_together={('functionally', 'technically')},
        ),
    ]
