# Generated by Django 5.0.6 on 2024-07-29 11:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_alter_approvalmatrix_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.AddField(
            model_name='item',
            name='detailed_description',
            field=models.TextField(default=1, help_text='A detailed description of the item.', validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9\\s.,\\\'"/-]*$', 'Only letters, numbers, spaces, ., \', ", /, and - are allowed in the description.')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='short_description',
            field=models.CharField(default=1, help_text='A brief description of the item.', max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9\\s.,\\\'"/-]*$', 'Only letters, numbers, spaces, ., \', ", /, and - are allowed in the description.')]),
            preserve_default=False,
        ),
    ]
