# Generated by Django 5.0.6 on 2024-07-30 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_remove_item_description_item_detailed_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='closed_date',
            new_name='resolved_date',
        ),
    ]
