# Generated by Django 5.0.6 on 2024-07-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_rename_closed_date_item_resolved_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='closed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('inprogress', 'In Progress'), ('pending', 'Pending'), ('Resolved', 'Resolved'), ('closed', 'Closed'), ('reopen', 'Re-Open')], default='open', max_length=20),
        ),
    ]
