# Generated by Django 5.0.6 on 2024-07-31 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0021_item_closed_date_alter_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='reopen_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
