# Generated by Django 5.0.6 on 2024-07-31 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0022_item_reopen_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='comments',
            new_name='closure_comments',
        ),
        migrations.AddField(
            model_name='item',
            name='reopen_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='resolver_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
