# Generated by Django 5.0.6 on 2024-09-27 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0023_rename_comments_item_closure_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('inprogress', 'In Progress'), ('pending', 'Pending'), ('Resolved', 'Resolved'), ('closed', 'Closed'), ('reopen', 'Re-Open'), ('seek-clarification', 'Seek Clarification')], default='open', max_length=20),
        ),
    ]
