# Generated by Django 5.0.6 on 2024-09-27 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0030_seekattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='seek_clarification_attachments',
        ),
    ]
