# Generated by Django 5.0.6 on 2024-09-27 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0032_seekclarificationhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='seek_clarification_cmnt',
        ),
    ]
