# Generated by Django 5.0.6 on 2024-09-28 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0034_seekattachment_created_at_seekattachment_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekattachment',
            name='clarification_history',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.seekclarificationhistory'),
            preserve_default=False,
        ),
    ]
