# Generated by Django 5.0.6 on 2024-09-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0035_seekattachment_clarification_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekattachment',
            name='clarification_type',
            field=models.CharField(choices=[('seek', 'Seek Clarification'), ('clarified', 'Clarified')], default='seek', help_text='Type of clarification (seeking or clarified).', max_length=20),
        ),
        migrations.AddField(
            model_name='seekclarificationhistory',
            name='clarified_comment',
            field=models.TextField(blank=True, help_text='Clarified comment.', null=True),
        ),
        migrations.AddField(
            model_name='seekclarificationhistory',
            name='status',
            field=models.CharField(choices=[('seek-clarification', 'Seek Clarification'), ('clarified', 'Clarified')], default='seek-clarification', max_length=20),
        ),
    ]
