# Generated by Django 5.0.6 on 2024-09-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0036_seekattachment_clarification_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seekattachment',
            name='clarification_type',
        ),
        migrations.AddField(
            model_name='seekattachment',
            name='attachment_type',
            field=models.CharField(choices=[('seek_clarification', 'Seek Clarification'), ('clarified', 'Clarified')], default='seek_clarification', max_length=20),
        ),
    ]
