# Generated by Django 5.0.6 on 2024-09-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0037_remove_seekattachment_clarification_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seekattachment',
            name='attachment_type',
        ),
        migrations.AddField(
            model_name='seekattachment',
            name='clarification_type',
            field=models.CharField(choices=[('seek', 'Seek Clarification'), ('clarified', 'Clarified')], default='seek', help_text='Type of clarification (seeking or clarified).', max_length=20),
        ),
    ]
