# Generated by Django 5.0.6 on 2024-10-05 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0042_ticketstatushistory_delete_itemstatushistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketStatusHistory',
        ),
    ]
