# Generated by Django 5.0.6 on 2024-10-05 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0046_rename_user_statushistory_changed_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statushistory',
            old_name='changed_by',
            new_name='created_by',
        ),
    ]
