# Generated by Django 5.0.6 on 2024-10-05 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0047_rename_changed_by_statushistory_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statushistory',
            old_name='created_by',
            new_name='changed_by',
        ),
    ]
