# Generated by Django 5.0.6 on 2024-10-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0050_statushistory_delete_statuschangehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
