# Generated by Django 4.2.4 on 2025-01-07 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0053_approvalmatrix_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='created_date',
            field=models.DateField(default=datetime.date.today, editable=False),
        ),
        migrations.AddField(
            model_name='item',
            name='ticket_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
