# Generated by Django 4.2.4 on 2025-01-21 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0055_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ageing_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='detailed_description',
            field=models.TextField(help_text='A detailed description of the item.'),
        ),
        migrations.AlterField(
            model_name='item',
            name='short_description',
            field=models.CharField(help_text='A brief description of the item.', max_length=255),
        ),
    ]
